export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
